// This file was autogenerated by calcdeps.py
goog.addDependency("../../soyutils_usegoog.js", ['soy', 'soy.StringBuilder'], ['goog.dom', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera/drvemera.js", ['drvemera.Plugin'], ['drvemera.view']);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera/scripts/controller.js", ['drvemera.controller'], ['drvemera.model']);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera/scripts/fixture.js", ['drvemera.fixture'], ['goog.array']);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera/scripts/model.js", ['drvemera.model'], ['drvemera.fixture']);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera/scripts/view.js", ['drvemera.view'], ['drvemera.controller', 'drvemera.model']);
goog.addDependency("../../../emax/goog/app.js", [], []);
goog.addDependency("../../../emax/goog/constants.js", ['constants'], []);
goog.addDependency("../../../emax/goog/environment.js", ['environment'], ['goog.uri.utils', 'goog.Uri']);
goog.addDependency("../../../emax/goog/router.js", ['router'], ['environment', 'goog.uri.utils', 'goog.Uri']);
goog.addDependency("../../../emax/goog/tools.js", ['tools'], []);
goog.addDependency("../../../../app/project/plugins/drivers/drvemera/drvemera.tpl.js", ['drvemera.locale'], ['soy', 'soy.StringBuilder']);
